version: 4:10.1
services:
  db:
    image: postgres:latest
    container_name: postgres
    volumes: 
      - ./api/data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
  
  # api:
  #   build: ./api
  #   container_name: api
  #   volumes:
  #     - ./api/data/db:/var/lib/postgresql/data
  #   ports:
  #     - "3000:3000"
  #   restart: unless-stopped
  #   depends_on:
  #     - db
  
  # web:
  #   build: ./frontend
  #   container_name: web
  #   ports:      
  #     - "8081:8081"
  #   restart: unless-stopped