export const main: string;
export const wrapper: string;
export const focused: string;
export const tasks: string;
export const task: string;
export const buttons: string;
export const edit: string;
export const done: string;
export const del: string;